### ISSUE TITLE
No link for the website

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/Online-Library#1]
the website needs to be deployed 🚀  so anyone can easily view it online, this these week's projects we use Github pages to deploy them ([here is part of the video on how to do it](https://youtu.be/8hrJ4oN1u_8?t=350)).

**having an index.html in the project is important in Github pages** since it is the root file for the deployment

**Comment by OmklthomAmara** [comment]
Fixed !!! thanks 👍
