### ISSUE TITLE
Contact form submit issue.

### ISSUE THREAD

**Issue by alaabashiyi** [WebAhead7/Online-Library#3]
The submit button in the contact is behaving weirdly enough that I could right my name in it. 
Fix: change the type from "submit-contact" to "submit" would fix this issue.

![image](https://user-images.githubusercontent.com/29834132/95428047-256f8a80-0951-11eb-8b7b-252f65aca685.png)

**Comment by OmklthomAmara** [comment]
Done, Thanks !!!
