### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by ahmad420** [WebAhead7/Online-Library#7]
*The background is overkill, red color is not matching with the overall dark theme.
*pages like the introduction /about us .. are too small so that is so much content on one page.
* footer :  position: fixed; should be removed.
*submit button is not a button.  <input type="submit-contact" ..  ===>  <input type="submit" ..
* title need change : <title>Document</title>  ==>  <title>Books & More</title> .

**Comment by Ammaryus** [comment]
solved, thanks Ahmad
